OperacaoConteiner/Models/ContainerModel.cs
using OperacaoConteiner.Models.Enums;

namespace OperacaoConteiner.Models
{
    public class ContainerModel
    {
        public int Id { get; set; }
        public string nomeCliente { get; set; }
        public string numeroContainer { get; set; }
        public TipoContainer tipoContainer { get; set; }
        public StatusContainer statusContainer { get; set; }
        public CategoriaContainer categoriaContainer { get; set; }
    }
}

OperacaoConteiner/Models/Enums/CategoriaContainer.cs
namespace OperacaoConteiner.Models.Enums
{
    public enum CategoriaContainer: int
    {
        Importação = 1,
        Exportação = 2
    }
}

OperacaoConteiner/Models/Enums/StatusContainer.cs
namespace OperacaoConteiner.Models.Enums
{
    public enum StatusContainer: int
    {
        Cheio = 1,
        Vazio = 2
    }
}

OperacaoConteiner/Models/Enums/TipoContainer.cs
namespace OperacaoConteiner.Models.Enums
{
    public enum TipoContainer: int
    {
        Container_20 = 1,
        Container_40 = 2
    }
}

OperacaoConteiner/Models/Enums/TipoMovimentacao.cs
namespace OperacaoConteiner.Models.Enums
{
    public enum TipoMovimentacao: int
    {
        Embarque = 1,
        Descarga = 2,
        Gate_in = 3,
        Gate_out = 4,
        Reposicionamento = 5,
        Pesagem = 6,
        Scanner = 7
    }
}

OperacaoConteiner/Models/ErrorViewModel.cs
using System;

namespace OperacaoConteiner.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OperacaoConteiner/Models/MovimentacaoContainerModel.cs
using System.Collections.Generic;

namespace OperacaoConteiner.Models
{
    public class MovimentacaoContainerModel
    {
        public MovimentacaoModel movimentacao { get; set; }
        public List<ContainerModel> todosContainer { get; set; }
    }
}

OperacaoConteiner/Models/MovimentacaoModel.cs
using OperacaoConteiner.Models.Enums;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace OperacaoConteiner.Models
{
    public class MovimentacaoModel
    {
        public int Id { get; set; }
        public TipoMovimentacao tipoMovimentação { get; set; }
        public DateTime DataInicio { get; set; }
        public DateTime DataFim { get; set; }

        [ForeignKey("container")]
        public int IdContainer { get; set; }
        public virtual ContainerModel container { get; set; }
    }
}

OperacaoConteiner/Controllers/ContainerController.cs
using Microsoft.AspNetCore.Mvc;
using OperacaoConteiner.Models;
using OperacaoConteiner.Repositorio;
using System.Collections.Generic;

namespace OperacaoConteiner.Controllers
{
    public class ContainerController : Controller
    {
        private readonly IContainerRepositorio _containerRepositorio;
        public ContainerController(IContainerRepositorio containerRepositorio)
        {
            _containerRepositorio = containerRepositorio;
        }
        public IActionResult Index()
        {
            List<ContainerModel> Listacontainer = _containerRepositorio.BuscarTodos();
            return View(Listacontainer);
        }
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(ContainerModel container)
        {
            try
            {
                TempData["mensagemSucesso"] = "Container cadastrado com sucesso!!";
                _containerRepositorio.Adicionar(container);
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["mensagemErro"] = "Ops, Erro ao cadastrar o container, tente novamente mais tarde!!, mais detalhes:"+erro.Message;
                return RedirectToAction("Index");
            }
        }

        public IActionResult Editar(int id)
        {
            ContainerModel container = _containerRepositorio.ListarContainerPorId(id);
            return View(container);
        }

        [HttpPost]
        public IActionResult Atualizar(ContainerModel container)
        {
            _containerRepositorio.Atualizar(container);
            return RedirectToAction("Index");
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            ContainerModel container = _containerRepositorio.ListarContainerPorId(id);
            return View(container);
        }

        public IActionResult apagar(int id)
        {
            _containerRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }
    }
}

OperacaoConteiner/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OperacaoConteiner.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace OperacaoConteiner.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OperacaoConteiner/Controllers/MovimentacaoController.cs
using Microsoft.AspNetCore.Mvc;
using OperacaoConteiner.Models;
using OperacaoConteiner.Repositorio;
using System.Collections.Generic;

namespace OperacaoConteiner.Controllers
{
    public class MovimentacaoController : Controller
    {
        private readonly IMovimentacaoRepositorio _movimentacaoRepositorio;
        private readonly IContainerRepositorio _containerRepositorio;
        public MovimentacaoController(IContainerRepositorio containerRepositorio, IMovimentacaoRepositorio movimentacaoRepositorio)
        {
            _containerRepositorio = containerRepositorio;
            _movimentacaoRepositorio = movimentacaoRepositorio;
        }
        public IActionResult Index()
        {
            List<MovimentacaoModel> Listacontainer = _movimentacaoRepositorio.BuscarTodos();
            return View(Listacontainer);
        }
        public IActionResult Cadastrar()
        {
            MovimentacaoModel movimentacao = new MovimentacaoModel();
            MovimentacaoContainerModel movimentacaoContainerModel = new MovimentacaoContainerModel();
            movimentacaoContainerModel.todosContainer = _containerRepositorio.BuscarTodos();
            movimentacaoContainerModel.movimentacao = movimentacao;
            return View(movimentacaoContainerModel);
        }

        [HttpPost]
        public IActionResult Cadastrar(MovimentacaoModel movimentacao)
        {
            try
            {
                TempData["mensagemSucesso"] = "Movimentação cadastrada com sucesso!!";
                _movimentacaoRepositorio.Adicionar(movimentacao);
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["mensagemErro"] = "Ops, Erro ao cadastrar a movimentação, tente novamente mais tarde!!, mais detalhes:" + erro.Message;
                return RedirectToAction("Index");
            }
        }

        public IActionResult Editar(int id)
        {
            MovimentacaoModel movimentacao = _movimentacaoRepositorio.ListarMovimentacaoPorId(id);
            return View(movimentacao);
        }

        [HttpPost]
        public IActionResult Atualizar(MovimentacaoModel movimentacao)
        {
            _movimentacaoRepositorio.Atualizar(movimentacao);
            return RedirectToAction("Index");
        }
        public IActionResult ApagarConfirmacao(int id)
        {
            MovimentacaoModel movimentacao = _movimentacaoRepositorio.ListarMovimentacaoPorId(id);
            return View(movimentacao);
        }

        public IActionResult Apagar(int id)
        {
            _movimentacaoRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        public IActionResult maisDetalhes(int id)
        {
            ContainerModel container = _containerRepositorio.ListarContainerPorId(id);
            return View(container);
        }
    }
}

OperacaoConteiner/Views/Container/ApagarConfirmacao.cshtml
@model ContainerModel
@{
    ViewData["Title"] = "Confirmação de apagar Container";
}

<div class="text-center">
    <h3>Realmente deseja apagar esse container?? @Model.nomeCliente</h3>
    <a class="btn btn-primary" asp-controller="Container" asp-action="apagar" asp-route-id="@Model.Id" role="button" >Apagar</a>
    <a class="btn btn-secondary" asp-controller="Container" asp-action="index" role="button" >Voltar</a>
</div>

OperacaoConteiner/Views/Container/ApagarConfirmação.cshtml
@model ContainerModel
@{
    ViewData["Title"] = "Confirmação de apagar Container";
}

<div class="text-center">
    <h3>Realmente deseja apagar esse container?? @Model.nomeCliente</h3>
    <a class="btn btn-primary" asp-controller="Container" asp-action="apagar" asp-route-id="@Model.Id" role="button" >Apagar</a>
    <a class="btn btn-secondary" asp-controller="Container" asp-action="index" role="button" >Voltar</a>
</div>

OperacaoConteiner/Views/Container/Cadastrar.cshtml
@using OperacaoConteiner.Models.Enums
@model ContainerModel
@{
    ViewData["Title"] = "Cadastrar Container";
}

<div class="text-center">
    <h1>Cadastro de Container</h1>
</div>

<form asp-controller="Container" asp-action="Cadastrar" method="post">
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" asp-for="nomeCliente" class="form-control" id="nome" placeholder="Digite o nome do container">
  </div>
  <div class="form-group">
    <label for="nome">Numero</label>
    <input type="text" asp-for="numeroContainer" class="form-control" id="numero" placeholder="GHJN1234567" maxlength = "11">
  </div>
  <div class="form-group">
    <label for="nome">Tipo</label>
    <select asp-for="tipoContainer" class="form-control" id="tipo"  asp-items="@(new SelectList(Enum.GetValues(typeof(TipoContainer))))"></select>
  </div>
  <div class="form-group">
    <label for="nome">Status</label>
    <select asp-for="statusContainer" class="form-control" id="status"   asp-items="@(new SelectList(Enum.GetValues(typeof(StatusContainer))))"></select>
  </div>
  <div class="form-group">
    <label for="nome">Categoria</label>
    <select asp-for="categoriaContainer" class="form-control" id="categoria" asp-items="@(new SelectList(Enum.GetValues(typeof(CategoriaContainer))))"></select>
  </div>
  <button type="submit" class="btn btn-success">Adicionar</button>
  <a class="btn btn-secondary" asp-controller="Container" asp-action="index" role="button" >Voltar</a>
</form>

OperacaoConteiner/Views/Container/Editar.cshtml
@using OperacaoConteiner.Models.Enums
@model ContainerModel
@{
    ViewData["Title"] = "Editar Container";
}

<div class="text-center">
    <h1>Editar Movimentação</h1>
</div>
<form asp-controller="Container" asp-action="Atualizar" method="post">
  <input type="hidden" asp-for="Id"/>
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" asp-for="nomeCliente" class="form-control" id="nome" placeholder="Digite o nome do container">
  </div>
  <div class="form-group">
    <label for="nome">Numero</label>
    <input type="text" asp-for="numeroContainer" class="form-control" id="numero" placeholder="GHJN1234567" maxlength = "11">
  </div>
  <div class="form-group">
    <label for="nome">Tipo</label>
    <select asp-for="tipoContainer" class="form-control" id="tipo"  asp-items="@(new SelectList(Enum.GetValues(typeof(TipoContainer))))"></select>
  </div>
  <div class="form-group">
    <label for="nome">Status</label>
    <select asp-for="statusContainer" class="form-control" id="status"   asp-items="@(new SelectList(Enum.GetValues(typeof(StatusContainer))))"></select>
  </div>
  <div class="form-group">
    <label for="nome">Categoria</label>
    <select asp-for="categoriaContainer" class="form-control" id="categoria" asp-items="@(new SelectList(Enum.GetValues(typeof(CategoriaContainer))))"></select>
  </div>
  <button type="submit" class="btn btn-success">Alterar</button>
  <a class="btn btn-secondary" asp-controller="Container" asp-action="index" role="button" >Voltar</a>
</form>

OperacaoConteiner/Views/Container/Index.cshtml
@model List<ContainerModel>
@{
    ViewData["Title"] = "Gerenciamento de Container";
}

<div class="text-center">
    <h2 class="display-4">Lista de Containers</h2>

    <br />
    <div class="text-left">
       <a asp-controller="Container" asp-action="Cadastrar" class="btn btn-success">Novo Container</a>
    </div>
    <br />
    @if(@TempData["mensagemSucesso"] != null)
    {
    <div class="alert alert-success alert-dismissible fade show" role="alert">
       @TempData["mensagemSucesso"]
       <button type="button" class="close" data-dismiss="alert">×</button>
    </div>
    }


    @if(@TempData["mensagemErro"] != null)
    {
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Holy guacamole!</strong> You should check in on some of those fields below.
         <button type="button" class="close" data-dismiss="alert">×</button>
    </div>    
    }

    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Cliente</th>
      <th scope="col">Numero</th>
      <th scope="col">Tipo</th>
      <th scope="col">Status</th>
      <th scope="col">Categoria</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
      @if(Model != null && Model.Any())
      {
          foreach (ContainerModel container in Model)
          {
             <tr>
                 <th scope="row">@container.Id</th>
                 <td>@container.nomeCliente</td>
                 <td>@container.numeroContainer</td>
                 <td>@container.tipoContainer</td>
                 <td>@container.statusContainer</td>
                 <td>@container.categoriaContainer</td>
                 <td>
                     <div class="text-center">
                         <a class="btn btn-primary" asp-action="Editar" asp-route-id="@container.Id">Editar</a>
                         <a class="btn btn-danger"  asp-action="ApagarConfirmacao" asp-route-id="@container.Id">Apagar</a>
                     </div>
                 </td>
             </tr>
          }
      }
  </tbody>
</table>

</div>

OperacaoConteiner/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo </h1>
    <p>Sistema de gerenciamento de Containers.</p>
</div>

OperacaoConteiner/Views/Movimentacao/ApagarConfirmacao.cshtml
@model MovimentacaoModel
@{
    ViewData["Title"] = "Confirmação de apagar Movimentação";
}

<div class="text-center">
    <h3>Realmente deseja apagar essa movimentação??</h3>
    <a class="btn btn-primary" asp-controller="Movimentacao" asp-action="apagar" asp-route-id="@Model.Id" role="button" >Apagar</a>
    <a class="btn btn-secondary" asp-controller="Movimentacao" asp-action="index" role="button" >Voltar</a>
</div>

OperacaoConteiner/Views/Movimentacao/Cadastrar.cshtml
@using OperacaoConteiner.Models.Enums

@model MovimentacaoContainerModel
@{
    ViewData["Title"] = "Cadastrar Movimentação";
}

<div class="text-center">
    <h1>Cadastro de Movimentação</h1>
</div>
<form asp-controller="Movimentacao" asp-action="Cadastrar" method="post">
  <div class="form-group">
    <label asp-for="@Model.movimentacao.tipoMovimentação">Tipo</label>
    <select asp-for="@Model.movimentacao.tipoMovimentação" class="form-control" id="tipo"  asp-items="@(new SelectList(Enum.GetValues(typeof(TipoMovimentacao))))"></select>
  </div>
  <div class="form-group">
    <label asp-for="@Model.movimentacao.DataInicio">Data de Inicio</label>
    <input asp-for="@Model.movimentacao.DataInicio" class="form-control" id="dataInicio">
  </div>
   <div class="form-group">
    <label asp-for="@Model.movimentacao.DataFim">Data do término</label>
    <input asp-for="@Model.movimentacao.DataFim" class="form-control" id="dataFim">
  </div>
  <div class="form-group">
    <label asp-for="@Model.movimentacao.IdContainer">Cliente</label>
    <select asp-for="@Model.movimentacao.IdContainer" class="form-control" id="idCliente">
        @{
            foreach (ContainerModel container in @Model.todosContainer)
            {
                <option value="@container.Id">@container.nomeCliente</option>
            }
        }
    </select>
  </div>
  <button type="submit" class="btn btn-success">Adicionar</button>
  <a class="btn btn-secondary" asp-controller="Movimentacao" asp-action="index" role="button" >Voltar</a>
</form>

OperacaoConteiner/Views/Movimentacao/Editar.cshtml
@using OperacaoConteiner.Models.Enums

@model MovimentacaoModel
@{
    ViewData["Title"] = "Editar Movimentação";
}

<div class="text-center">
    <h1>Editar Movimentação</h1>
</div>
<form asp-controller="Movimentacao" asp-action="Atualizar" method="post">
    <input type="hidden" asp-for="IdContainer"/>
    <input type="hidden" asp-for="Id"/>
  <div class="form-group">
    <label asp-for="tipoMovimentação">Tipo</label>
    <select asp-for="tipoMovimentação" class="form-control" id="tipo"  asp-items="@(new SelectList(Enum.GetValues(typeof(TipoMovimentacao))))"></select>
  </div>
  <div class="form-group">
    <label asp-for="DataInicio">Data de Inicio</label>
    <input asp-for="DataInicio" class="form-control" id="dataInicio">
  </div>
   <div class="form-group">
    <label asp-for="DataFim">Data do término</label>
    <input asp-for="DataFim" class="form-control" id="dataFim">
  </div>
  <button type="submit" class="btn btn-success">Alterar</button>
  <a class="btn btn-secondary" asp-controller="Movimentacao" asp-action="index" role="button" >Voltar</a>
</form>

OperacaoConteiner/Views/Movimentacao/Index.cshtml
@model List<MovimentacaoModel>
@{
    ViewData["Title"] = "Gerenciamento de Movimentacao";
}

<div class="text-center">
    <h2 class="display-4">Lista de Movimentacao</h2>

    <br />
    <div class="text-left">
       <a asp-controller="Movimentacao" asp-action="Cadastrar" class="btn btn-success">Nova Movimentação</a>
    </div>
    <br />
    @if(@TempData["mensagemSucesso"] != null)
    {
    <div class="alert alert-success alert-dismissible fade show" role="alert">
       @TempData["mensagemSucesso"]
       <button type="button" class="close" data-dismiss="alert">×</button>
    </div>
    }


    @if(@TempData["mensagemErro"] != null)
    {
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Holy guacamole!</strong> You should check in on some of those fields below.
         <button type="button" class="close" data-dismiss="alert">×</button>
    </div>    
    }
    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Tipo Movimentação</th>
      <th scope="col">Data de inicio</th>
      <th scope="col">Data de fim</th>
      <th scope="col">Id do Cliente</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody> 
      @if(Model != null && Model.Any())
      {
          foreach (MovimentacaoModel movimentacao in Model)
          {
             <tr>
                 <th scope="row">@movimentacao.Id</th>
                 <td>@movimentacao.tipoMovimentação</td>
                 <td>@movimentacao.DataInicio</td>
                 <td>@movimentacao.DataFim</td>
                 <td>@movimentacao.IdContainer</td>
                 <td>
                     <div class="text-center">
                         <a class="btn btn-primary" asp-action="Editar" asp-route-id="@movimentacao.Id">Editar</a>
                         <a class="btn btn-danger"  asp-action="ApagarConfirmacao" asp-route-id="@movimentacao.Id">Apagar</a>
                         <a class="btn btn-info"  asp-action="maisDetalhes" asp-route-id="@movimentacao.IdContainer">Detalhes</a>
                     </div>
                 </td>
             </tr>
          }
      }
  </tbody>
</table>

</div>

OperacaoConteiner/Views/Movimentacao/maisDetalhes.cshtml
@model ContainerModel
@{
    ViewData["Title"] = "Mais Detalhes";
}

<div class="text-center">
    <h1>Mais Detalhes sobre o cliente</h1>
</div>
<form>
  <div class="form-group">
    <b>Nome do Cliente: </b>
    <label>@Model.nomeCliente</label>
  </div>
  <div class="form-group">
    <b>Numero do Container: </b>
    <label>@Model.numeroContainer</label>
  </div>
  <div class="form-group">
    <b>Tipo do Container: </b>
    <label>@Model.tipoContainer</label>
  </div>
  <div class="form-group">
    <b>Status do Container: </b>
    <label>@Model.statusContainer</label>
  </div>
  <div class="form-group">
    <b>Categoria do Container: </b>
    <label>@Model.categoriaContainer</label>
  </div>
  <a class="btn btn-secondary" asp-controller="Movimentacao" asp-action="index" role="button" >Voltar</a>
</form>

OperacaoConteiner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Operacao de Conteiner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Operacao de Conteiner</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Container" asp-action="index">Container</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movimentacao" asp-action="index">Movimentação</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OperacaoConteiner 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>